CREATE TABLE IF NOT EXISTS Boisson ([d_id] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [d_name] varchar(20) not null, [d_sprice] decimal(9,2) not null, [d_pprice] decimal(9,2) not null, [d_stock] smallint not null, [d_stockm] smallint not null,[d_seuil] smallint not null,[d_descr_en] varchar(140) not null,[d_descr_fr] varchar(140) not null,[d_type] varchar(20) not null);
INSERT INTO Boisson ([d_name], [d_sprice], [d_pprice], [d_stock], [d_stockm], [d_seuil], [d_descr_en],[d_descr_fr], [d_type]) VALUES('Hoegaarden', 3.5 , 2.5, 15, 45, 10, 'Delicious bear, softly sweet','Excellente bière sucrée', 'Biere');
INSERT INTO Boisson ([d_name], [d_sprice], [d_pprice], [d_stock], [d_stockm], [d_seuil], [d_descr_en],[d_descr_fr], [d_type]) VALUES('Coca-Cola', 1.5 , 0.5, 25, 100, 20, 'Soft sparkling and energetic','Soft pétillant et revigorant', 'Soft');
INSERT INTO Boisson ([d_name], [d_sprice], [d_pprice], [d_stock], [d_stockm], [d_seuil], [d_descr_en],[d_descr_fr], [d_type]) VALUES('Chateau Gay-Lussac', 5.5 , 2.5, 10, 20, 5, 'French wine of great quality' ,'Vin francais de grande qualite', 'Vin');
INSERT INTO Boisson ([d_name], [d_sprice], [d_pprice], [d_stock], [d_stockm], [d_seuil], [d_descr_en],[d_descr_fr], [d_type]) VALUES('Orval', 3.5 , 2.5, 20, 45, 10, 'Belgian classic','Grand classique Belge', 'Biere');
INSERT INTO Boisson ([d_name], [d_sprice], [d_pprice], [d_stock], [d_stockm], [d_seuil], [d_descr_en],[d_descr_fr], [d_type]) VALUES('Fanta', 1.5 , 0.5, 5, 100, 20, 'Orange juice with bubbles','Soft pétillant et revigorant', 'Soft');
INSERT INTO Boisson ([d_name], [d_sprice], [d_pprice], [d_stock], [d_stockm], [d_seuil], [d_descr_en],[d_descr_fr], [d_type]) VALUES('Piquette', 4.5 , 1.5, 2, 20, 5, 'Cheap wine','Vin cheap', 'Vin');
INSERT INTO Boisson ([d_name], [d_sprice], [d_pprice], [d_stock], [d_stockm], [d_seuil], [d_descr_en],[d_descr_fr], [d_type]) VALUES('Chimay', 3.5 , 1.5, 1, 10, 2, 'Bear made with love and passion','Biere brassée avec amour et passion', 'Biere');
CREATE TABLE IF NOT EXISTS [users] ( [u_id] INTEGER PRIMARY KEY NOT NULL , [u_name] TEXT NOT NULL DEFAULT ( NULL ) , [u_password] TEXT NOT NULL DEFAULT ( NULL ), [u_status] TEXT NOT NULL DEFAULT "user", [u_ismanager] SMALLINT NOT NULL DEFAULT ( 0 ));
INSERT INTO "users" VALUES(1, 'Manager', 'manager', 'barman', 1);
INSERT INTO "users" VALUES(2,'Kim Mens','lsinf1225','client', 0);
INSERT INTO "users" VALUES(3, 'Zelie', '123', 'client', 0);
INSERT INTO "users" VALUES(4, 'Barman', 'barman', 'barman', 0);
INSERT INTO "users" VALUES(5, 'Anonyme', 'anonyme', 'user', 0);
CREATE TABLE IF NOT EXISTS [orders] ( [o_id] INTEGER PRIMARY KEY NOT NULL , [b_id] INTEGER NOT NULL, [u_id] INTEGER NOT NULL, [o_amountorder] DOUBLE NOT NULL DEFAULT (0.0), [o_table] SMALLINT NOT NULL, [o_date] DATE NOT NULL, [o_issent] SMALLINT NOT NULL DEFAULT ( 0 ), [o_isserved] SMALLINT NOT NULL DEFAULT ( 0 ), [o_ispaid] SMALLINT NOT NULL DEFAULT (0 ));
INSERT INTO "orders" VALUES(1, 4, 3, 15.5, 4, "2015-04-30 14:52:00", 1, 0, 0);
INSERT INTO "orders" VALUES(2, 1, 2, 12.5, 7, "2015-04-30 15:52:00", 1, 1, 1);
CREATE TABLE IF NOT EXISTS [details] ( [det_id] INTEGER PRIMARY KEY NOT NULL , [det_quant] SMALLINT NOT NULL , [d_id] INTEGER NOT NULL , [o_id] INTEGER NOT NULL );
CREATE TABLE IF NOT EXISTS [timetables] ( [t_id] INTEGER PRIMARY KEY NOT NULL , [b_id] SMALLINT NOT NULL, [t_day] INTEGER NOT NULL, [t_begin] TEXT DEFAULT ( NULL ), [t_end] TEXT DEFAULT ( NULL ));